### PR TITLE
Fix so secure channel is able to resume..

### PR DESCRIPTION
**Pull request by silchas**
Problem:
If CP is reset/restarted when it's up and running in secure channel mode, communication will immediately fail when started again because Pollcommand is sent before secure channel is set up.  

Solution:
Moved Pollcommand if sequence == 0 after secure channel init checks,  so communication can be resumed if CP (but not the PD's) have been reset/restarted.

### CODE REVIEW

**Comment by bytedreamer** [comment]
Thanks, did you test this fix on secure channel devices? I had some issues with secure channel reconnects before. 

https://github.com/bytedreamer/OSDP.Net/issues/4

**Comment by silchas** [comment]
> 
> 
> Thanks, did you test this fix on secure channel devices? I had some issues with secure channel reconnects before.
> 
> #4

I've tested it against our own embedded devices in secure mode, which are running code using an osdp library from one of our partners. After above fix there have been no problems with reconnects at all.

Our use case for this library is setup, test and validation of our devices in manufacturing.

**Comment by bytedreamer** [comment]
I had some discussions with another OSDP developer about the best way to handle security reinitialization. The device should be able to handle either method when there is a CP reset. The important thing is the security channel is reinitialized.

Your change removes the need for sending additional poll command before the initialization of a security channel. Which make sense, except the sequence check for zero should happen after the initialization (osdp_CHLNG) and before the final establishment command (osdp_SCRYPT). The establishment command should never be sent on sequence zero. 

Please remove the console output commands, since this is a general purpose library. I had sent polling to the log for debugging. I then remove it when committing code, since it basically makes the log output unreadable. Another method is to add a breakpoint that only logs to output when passed.

**Comment by silchas** [comment]
So just that i get it right: 

            if (MessageControl.Sequence == 0) 
            {
                Console.WriteLine("polling");
                return new PollCommand(Address);
            }

should go between IsInitialized and IsEstablished checks?

And yea i forgot to remove the console outputs, will fix

**Pull request merged**
